//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryAutomation1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBook
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string Enrollment { get; set; }
        public Nullable<bool> Issue { get; set; }
    }
}
